"""Add view_name to PlayEvent

Revision ID: 13f115f4d409
Revises: 2a10a1f39710
Create Date: 2025-05-02 18:28:12.334518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f115f4d409'
down_revision: Union[str, None] = '2a10a1f39710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_events', sa.Column('view_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_events', 'view_name')
    # ### end Alembic commands ###
