"""create timer

Revision ID: 2643fa27bf00
Revises: c9b8043b9944
Create Date: 2026-09-28 23:27:53.878699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2643fa27bf00'
down_revision: Union[str, None] = 'c9b8043b9944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('play_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timers')),
    sa.UniqueConstraint('id', name=op.f('uq_timers_id')),
    sa.UniqueConstraint('play_id', name=op.f('uq_timers_play_id'))
    )
    op.drop_index('play_events_play_id', table_name='play_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('play_events_play_id', 'play_events', ['play_id', 'typename'], unique=False)
    op.drop_table('timers')
    # ### end Alembic commands ###
