"""Add index for play event

Revision ID: 2a10a1f39710
Revises: 0e83e4bdee98
Create Date: 2025-04-30 11:32:52.742077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a10a1f39710'
down_revision: Union[str, None] = '0e83e4bdee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('play_events_play_id', 'play_events', ['play_id', 'typename'], unique=False)
    op.create_unique_constraint(op.f('uq_play_events_id'), 'play_events', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_play_events_id'), 'play_events', type_='unique')
    op.drop_index('play_events_play_id', table_name='play_events')
    # ### end Alembic commands ###
