"""Add owner to the game

Revision ID: 2ce8788c305a
Revises: b4f80695f997
Create Date: 2025-03-30 21:48:38.728486

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce8788c305a"
down_revision: Union[str, None] = "b4f80695f997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_app_users_id"), "app_users", ["id"])
    op.add_column("games", sa.Column("user_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_games_user_id_app_users"), "games", type_="foreignkey")
    op.drop_column("games", "user_id")
    # ### end Alembic commands ###
