"""Create player table

Revision ID: 35d11fd9227d
Revises: 051492999a25
Create Date: 2025-03-23 01:41:34.855168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d11fd9227d'
down_revision: Union[str, None] = '051492999a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_players_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('id', name=op.f('uq_players_id'))
    )
    op.create_unique_constraint(op.f('uq_questions_id'), 'questions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_questions_id'), 'questions', type_='unique')
    op.drop_table('players')
    # ### end Alembic commands ###
