"""Create instance table

Revision ID: 3e412320b832
Revises: 625ef3ab0c22
Create Date: 2025-03-23 01:34:58.283541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e412320b832'
down_revision: Union[str, None] = '625ef3ab0c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_instances_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('id', name=op.f('uq_instances_id'))
    )
    op.create_unique_constraint(op.f('uq_profiles_id'), 'profiles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_profiles_id'), 'profiles', type_='unique')
    op.drop_table('instances')
    # ### end Alembic commands ###
