"""Add PlayEvents payload

Revision ID: 58535c885879
Revises: 13f115f4d409
Create Date: 2025-05-04 15:34:03.865269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58535c885879'
down_revision: Union[str, None] = '13f115f4d409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_events', sa.Column('payload', sa.JSON(), nullable=True))
    op.drop_column('play_events', 'team_id')
    op.drop_column('play_events', 'money')
    op.drop_column('play_events', 'view_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_events', sa.Column('view_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('play_events', sa.Column('money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('play_events', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('play_events', 'payload')
    # ### end Alembic commands ###
