"""Create profile table

Revision ID: 625ef3ab0c22
Revises: 74225fb151ff
Create Date: 2025-03-23 01:25:27.378251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625ef3ab0c22'
down_revision: Union[str, None] = '74225fb151ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('id', name=op.f('uq_profiles_id'))
    )
    op.create_unique_constraint(op.f('uq_games_id'), 'games', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_games_id'), 'games', type_='unique')
    op.drop_table('profiles')
    # ### end Alembic commands ###
