"""Add index for questions

Revision ID: 94c06ec1c2c6
Revises: 2ce8788c305a
Create Date: 2025-03-31 17:25:28.930770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c06ec1c2c6'
down_revision: Union[str, None] = '2ce8788c305a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_questions_game_id'), 'questions', ['game_id'], unique=False)
    op.drop_constraint('fk_questions_game_id_games', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_questions_game_id_games', 'questions', 'games', ['game_id'], ['id'])
    op.drop_index(op.f('ix_questions_game_id'), table_name='questions')
    # ### end Alembic commands ###
