"""Light delete for games

Revision ID: c11c099e09c4
Revises: ea8106296230
Create Date: 2025-03-30 13:32:54.442099

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c11c099e09c4"
down_revision: Union[str, None] = "ea8106296230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_events_id"), "events", ["id"])
    op.add_column("games", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "is_deleted")
    op.drop_constraint(op.f("uq_events_id"), "events", type_="unique")
    # ### end Alembic commands ###
